name: nnt
channels:
  - defaults
  - conda-forge
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - colorama=0.4.1
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ipython_genutils=0.2.0
  - jinja2=2.10.1
  - jupyter_core=4.5.0
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbformat=4.4.0
  - notebook=6.0.0
  - openssl=1.1.1c
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pickleshare=0.7.5
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - pygments=2.4.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - zeromq=4.3.1
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - astroid==2.2.5
    - avryp==0.0.10
    - configparser==4.0.2
    - cycler==0.10.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.22.0
    - h5py==2.9.0
    - ipykernel==5.1.2
    - ipython==7.8.0
    - isort==4.3.21
    - jedi==0.15.1
    - joblib==0.13.2
    - jsonschema==3.0.2
    - jupyter-client==5.3.3
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.1
    - markdown==3.1.1
    - matplotlib==3.1.1
    - mccabe==0.6.1
    - mock==3.0.5
    - nbconvert==5.6.0
    - numexpr==2.6.9
    - numpy==1.16.4
    - opt-einsum==3.1.0
    - pandas==0.25.0
    - parso==0.5.1
    - pillow==6.2.1
    - pip==19.2.1
    - protobuf==3.9.1
    - pydot==1.4.1
    - pylint==2.3.1
    - pyparsing==2.4.2
    - pyserial==3.4
    - pytz==2019.2
    - pyyaml==5.1.2
    - pyzmq==18.1.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - six==1.12.0
    - sklearn==0.0
    - tables==3.5.2
    - tensorboard==2.0.0
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.0
    - termcolor==1.1.0
    - torch==1.3.1+cpu
    - torchvision==0.4.2+cpu
    - typed-ast==1.4.0
    - werkzeug==0.15.5
    - wrapt==1.11.2