name: nnt
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cpuonly
  - pytorch=1.9.0
  - jupyterlab
  - torchvision=0.10.0
  - torchaudio=0.9.0
  - pip=21.2.4
  - pip:
    - matplotlib
    - nbconvert
    - numpy
    - pillow
    - pyserial
    - scikit-learn
    - scipy
    - tensorflow==2.6.0
