name: nnt_36_cntk
channels:
  - defaults
  - conda-forge
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - certifi=2019.11.28
  - colorama=0.4.3
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - libsodium=1.0.16
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - more-itertools=8.2.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - pygments=2.5.2
  - pyrsistent=0.15.7
  - python=3.6.10
  - python-dateutil=2.8.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - send2trash=1.5.0
  - setuptools=45.1.0
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tornado=6.0.3
  - traitlets=4.3.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.1
  - zipp=2.1.0
  - pip:
    - cntk==2.7
    - numpy==1.18.1
    - scipy==1.4.1